### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by ghost** [BloodAxe/xView3-The-First-Place-Solution#2]
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I am not sure how/where to modify it. Thanks!

**Comment by BloodAxe** [comment]
I am not sure how you trying to load weights, but I assume you don't use `nvidia-docker` engine to run the container. You have two options: Either use GPU-enabled environment to run the model or update the code to use `device="cpu"` when calling torch.load(..., device="cpu") and model.to(device="cpu")
