### ISSUE TITLE
Is it possible to provide weigths of the trained models ?

### ISSUE THREAD

**Issue by Abdoulaye-Koroko** [BloodAxe/xView3-The-First-Place-Solution#4]
Hello,

Thank you for this great work and congratulations for your first place in the challenge. I am wondering if it is possible for you to provide the weights of your trained models so that we can do inference without the need of retraining or at least have a started pre-trained weights for further fine-tuning. You have mentioned in the documentation that you provided the weights but I could find them in the repo.

Thank you for your consideration

**Comment by BloodAxe** [comment]
Weights were released and available here: https://github.com/BloodAxe/xView3-The-First-Place-Solution/releases
